fix DNS issues in release-hatch tests

diff --git a/tests/check-release-hatch b/tests/check-release-hatch
--- a/tests/check-release-hatch
+++ b/tests/check-release-hatch
@@ -1,12 +1,25 @@
 #!/bin/bash
+
+
+# set DNS for RELEASE_HOST to 127.0.0.1
+source <(cat /srv/jobrunner/environ/*.env)
+HOSTNAME="$(echo "$RELEASE_HOST" | cut -d'/' -f3 | cut -d':' -f1)"
+grep -q "$HOSTNAME" /etc/hosts || echo "127.0.0.1 $HOSTNAME" >> /etc/hosts
+
 # run release-hatch tests
 docker-compose -f ~jobrunner/release-hatch/docker-compose.yaml run --rm release-hatch-test
 
 # check CORS preflight
-curl -s --fail https://localhost -X OPTIONS \
+cors_check=0
+curl -s --fail $RELEASE_HOST -X OPTIONS \
   -H 'Access-Control-Request-Method: GET' \
   -H 'Access-Control-Request-Headers: authorization' \
   -H 'Origin: https://jobs.opensafely.org' \
   -H 'Sec-Fetch-Mode: cors' \
   -H 'Sec-Fetch-Site: same-site' \
-  -H 'Sec-Fetch-Dest: empty'
+  -H 'Sec-Fetch-Dest: empty' || cors_check=$?
+
+if test $cors_check != 0; then
+   echo "CORS preflight check failed with exit code $cors_check"
+   exit $cors_check
+fi
